[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
eth = "https://eth.llamarpc.com"
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
